#! /usr/bin/env bash

set -eu -o pipefail

#
# Run the scan.lambda_handler locally in a docker container
#

if [ $# -lt 2 ]; then
  echo 1>&2 "$0: not enough arguments. Please provide BUCKET and KEY"
  exit 1
fi

TEST_BUCKET=$1
TEST_KEY=$2
EVENT="{\"Records\": [{\"s3\": {\"bucket\": {\"name\": \"${TEST_BUCKET}\"}, \"object\": {\"key\": \"${TEST_KEY}\"}}}]}"
echo "Sending S3 event: ${EVENT}"

# Verify that the file exists first
aws s3 ls "s3://${TEST_BUCKET}/${TEST_KEY}"

NAME="antivirus-scan"

docker run --rm \
  -e AV_DEFINITION_S3_BUCKET \
  -e AV_DEFINITION_S3_PREFIX \
  -e AV_DELETE_INFECTED_FILES \
  -e AV_PROCESS_ORIGINAL_VERSION_ONLY \
  -e AV_SCAN_START_METADATA \
  -e AV_SCAN_START_SNS_ARN \
  -e AV_SIGNATURE_METADATA \
  -e AV_STATUS_CLEAN \
  -e AV_STATUS_INFECTED \
  -e AV_STATUS_METADATA \
  -e AV_STATUS_SNS_ARN \
  -e AV_STATUS_SNS_PUBLISH_CLEAN \
  -e AV_STATUS_SNS_PUBLISH_INFECTED \
  -e AV_TIMESTAMP_METADATA \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_DEFAULT_REGION \
  -e AWS_REGION \
  -e AWS_SECRET_ACCESS_KEY \
  -e AWS_SESSION_TOKEN \
  --memory="${MEM}" \
  --memory-swap="${MEM}" \
  --cpus="${CPUS}" \
  --name="${NAME}" \
  -p 9000:8080 -d bucket-antivirus-function-clamd

CONTAINER=`docker ps | grep bucket-antivirus-function-clamd | cut -d " " -f 1`
echo "Container started, id is: ${CONTAINER}"

curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d "${EVENT}"

echo "Finished scan."
echo "Killing container ${CONTAINER}"
docker kill $CONTAINER